//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKTF_e_Aduan.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDatabaseEntities : DbContext
    {
        public MyDatabaseEntities()
            : base("name=MyDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<complaint> complaints { get; set; }
        public virtual DbSet<staff> staffs { get; set; }
        public virtual DbSet<studentProfile> studentProfiles { get; set; }
        public virtual DbSet<technician> technicians { get; set; }
        public virtual DbSet<typeOfComplaint> typeOfComplaints { get; set; }
        public virtual DbSet<typeOfDamage> typeOfDamages { get; set; }
    }
}
