//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKTF_e_Aduan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public string staffId { get; set; }
        public string staffName { get; set; }
        public string staffDesignation { get; set; }
        public string staffEmail { get; set; }
        public string staffPhoneNo { get; set; }
    }
}
