//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKTF_e_Aduan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentProfile
    {
        public int matricNo { get; set; }
        public string name { get; set; }
        public string ic { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public string programme { get; set; }
        public string email { get; set; }
        public string faculty { get; set; }
    }
}
