//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKTF_e_Aduan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public string matricNo { get; set; }
        public string name { get; set; }
        public Nullable<int> ic { get; set; }
        public Nullable<int> phone { get; set; }
        public string address { get; set; }
        public string programme { get; set; }
        public string email { get; set; }
        public string faculty { get; set; }
    }
}
